//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sattarov_Глазки_save
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }

        public int SaleCount { get
            {
                return ProductSale.Count;
            } }
        public string TypeAgent { get
            {
                return AgentType.Title;
            }}
        public int SalesForYears
        {
            get
            {
                int s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    TimeSpan diffecrenceWithoutTime = DateTime.Today.Date - p.SaleDate;
                    if ((int)diffecrenceWithoutTime.TotalDays <= 360)
                        s += p.ProductCount;
                }
                return s;
            }
        }
        public int SalesForAllTime
        {
            get
            {
                return ProductSale.Sum(p => p.ProductCount);
            }
        }
        public int Discount
        {
            get
            {
                int totalSales = SalesForAllTime;
                if (totalSales > 500000) return 25;
                else if (totalSales > 150000) return 20;
                else if (totalSales > 50000) return 10;
                else if (totalSales > 10000) return 5;
                else return 0;
            }
            }
        public string FonStyle
        {
            get
            {
                if (Discount > 25)
                    return "LightGreen";
                else
                    return "White";
            }
        }


        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
